[package]
name = "app-template"
version = "0.1.0"
authors = ["Dot HQ <contact@dothq.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.gtk]
version = "0.9"
features = ["v3_22"]
